### ISSUE TITLE
EASY

### ISSUE THREAD

**Issue by darkdarcool** [TheQuackyDuck/Try-To-Find-The-Something#2]
I’m on my phone and went to find the link and got it first try blindly! EZ

**Comment by TheQuackyDuck** [comment]
~~finally my repos are getting more attention~~

well ur SMORT then. The next one won't be so easy cuz my javascript skills are improving 😈

**Comment by darkdarcool** [comment]
Hmmmmmmm, that seems like a challenge 😎, I can help with a random generator that takes the text and places random html with a link (<a> tag) in it in react :)

**Comment by TheQuackyDuck** [comment]
that would be awesome but the other ones won't be a link anymore xP, but you can try, lemme me just send a collaborator invite...

**Comment by TheQuackyDuck** [comment]
added you.

**Comment by darkdarcool** [comment]
kk, I won’t be on for like an hour, I’m on my phone and I’m at some small family gathering I don’t wanna be at :(

**Comment by darkdarcool** [comment]
Also can I have repl inv?

**Comment by TheQuackyDuck** [comment]
oooooooooooooooooooooooooooooooooooooooooooooooooooooh about that, i used vs code to do it so.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by darkdarcool** [comment]
Live share bruh
